// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Onboarding.Applications.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.Onboarding.Applications
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\onboarding\applications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Griffin.Client.v0.onboarding.applications.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Griffin.Client.V0.Onboarding.Applications.Item.OnboardingApplicationItemRequestBuilder"/></returns>
        public global::Griffin.Client.V0.Onboarding.Applications.Item.OnboardingApplicationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("onboarding%2Dapplication%2Did", position);
                return new global::Griffin.Client.V0.Onboarding.Applications.Item.OnboardingApplicationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Onboarding.Applications.ApplicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/onboarding/applications", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Onboarding.Applications.ApplicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplicationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/onboarding/applications", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
