// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.Simulation.Organizations.Item.CopRequest
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\simulation\organizations\{organization-id}\cop-request
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopRequestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The simulate property</summary>
        public global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.SimulateRequestBuilder Simulate
        {
            get => new global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.SimulateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.CopRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopRequestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.CopRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopRequestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
