// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.LegalPersons
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFilterApplicationStatusEqQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "referred")]
        #pragma warning disable CS1591
        Referred,
        #pragma warning restore CS1591
        [EnumMember(Value = "errored")]
        #pragma warning disable CS1591
        Errored,
        #pragma warning restore CS1591
        [EnumMember(Value = "declined")]
        #pragma warning disable CS1591
        Declined,
        #pragma warning restore CS1591
        [EnumMember(Value = "submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "accepted")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
    }
}
