// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.LegalPersons
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFilterHasQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "application-status")]
        #pragma warning disable CS1591
        ApplicationStatus,
        #pragma warning restore CS1591
    }
}
