// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Organizations.Item.LegalPersons.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Organizations.Item.LegalPersons
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\organizations\{organization-id}\legal-persons
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LegalPersonsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The search property</summary>
        public global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder Search
        {
            get => new global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegalPersonsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/legal-persons{?filter%5Bapplication%2Dstatus%5D%5Beq%5D*,filter%5Bhas%5D%5B%5D*,filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D*,include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegalPersonsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/legal-persons{?filter%5Bapplication%2Dstatus%5D%5Beq%5D*,filter%5Bhas%5D%5B%5D*,filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D*,include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a paginated list of all legal persons for the given organization.By default, results are sorted descending by `created-at` (newest first). To sort ascending by `created-at`, provide a `?sort=created-at` query parameter. 
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsGetResponse?> GetAsLegalPersonsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsGetResponse> GetAsLegalPersonsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsGetResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a paginated list of all legal persons for the given organization.By default, results are sorted descending by `created-at` (newest first). To sort ascending by `created-at`, provide a `?sort=created-at` query parameter. 
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsLegalPersonsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse?> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Legal Person. A collection of [Claims](#tag/Claims) may be provided.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostResponse?> PostAsLegalPersonsPostResponseAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostResponse> PostAsLegalPersonsPostResponseAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Legal Person. A collection of [Claims](#tag/Claims) may be provided.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsLegalPersonsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse?> PostAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse> PostAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a paginated list of all legal persons for the given organization.By default, results are sorted descending by `created-at` (newest first). To sort ascending by `created-at`, provide a `?sort=created-at` query parameter. 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new Legal Person. A collection of [Claims](#tag/Claims) may be provided.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a paginated list of all legal persons for the given organization.By default, results are sorted descending by `created-at` (newest first). To sort ascending by `created-at`, provide a `?sort=created-at` query parameter. 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LegalPersonsRequestBuilderGetQueryParameters 
        {
            /// <summary>Return only legal persons with the given application-status.</summary>
            [Obsolete("This property is deprecated, use FilterapplicationStatuseqAsGetFilterApplicationStatusEqQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bapplication%2Dstatus%5D%5Beq%5D")]
            public string? FilterapplicationStatuseq { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bapplication%2Dstatus%5D%5Beq%5D")]
            public string FilterapplicationStatuseq { get; set; }
#endif
            /// <summary>Return only legal persons with the given application-status.</summary>
            [QueryParameter("filter%5Bapplication%2Dstatus%5D%5Beq%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetFilterApplicationStatusEqQueryParameterType? FilterapplicationStatuseqAsGetFilterApplicationStatusEqQueryParameterType { get; set; }
            /// <summary>Return only legal persons with the given attributes.</summary>
            [Obsolete("This property is deprecated, use FilterhasAsGetFilterHasQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bhas%5D%5B%5D")]
            public string[]? Filterhas { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bhas%5D%5B%5D")]
            public string[] Filterhas { get; set; }
#endif
            /// <summary>Return only legal persons with the given attributes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bhas%5D%5B%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetFilterHasQueryParameterType[]? FilterhasAsGetFilterHasQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bhas%5D%5B%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetFilterHasQueryParameterType[] FilterhasAsGetFilterHasQueryParameterType { get; set; }
#endif
            /// <summary>Return only legal persons with the given legal-person-status.</summary>
            [Obsolete("This property is deprecated, use FilterlegalPersonStatusinAsGetFilterLegalPersonStatusInQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D")]
            public string[]? FilterlegalPersonStatusin { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D")]
            public string[] FilterlegalPersonStatusin { get; set; }
#endif
            /// <summary>Return only legal persons with the given legal-person-status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetFilterLegalPersonStatusInQueryParameterType[]? FilterlegalPersonStatusinAsGetFilterLegalPersonStatusInQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Bin%5D%5B%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetFilterLegalPersonStatusInQueryParameterType[] FilterlegalPersonStatusinAsGetFilterLegalPersonStatusInQueryParameterType { get; set; }
#endif
            /// <summary>For each legal person returned, include its latest verification (if one exists), any roles in companies (significant control or directorship), and/or its latest risk rating (if one exists) in the response under the `included` attribute.</summary>
            [Obsolete("This property is deprecated, use IncludeAsGetIncludeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string[] Include { get; set; }
#endif
            /// <summary>For each legal person returned, include its latest verification (if one exists), any roles in companies (significant control or directorship), and/or its latest risk rating (if one exists) in the response under the `included` attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetIncludeQueryParameterType[]? IncludeAsGetIncludeQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetIncludeQueryParameterType[] IncludeAsGetIncludeQueryParameterType { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public byte[]? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public byte[] Pageafter { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bbefore%5D")]
            public byte[]? Pagebefore { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bbefore%5D")]
            public byte[] Pagebefore { get; set; }
#endif
            [QueryParameter("page%5Bsize%5D")]
            public long? Pagesize { get; set; }
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("sort")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LegalPersonsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.LegalPersonsRequestBuilder.LegalPersonsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LegalPersonsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
