// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.CompaniesHouse.Companies;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.CompaniesHouse
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\companies-house
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompaniesHouseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The companies property</summary>
        public global::Griffin.Client.V0.CompaniesHouse.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Griffin.Client.V0.CompaniesHouse.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.CompaniesHouseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesHouseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/companies-house", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.CompaniesHouseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesHouseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/companies-house", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
