// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Webhooks.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhookGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Activate a webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivateWebhookUrl { get; set; }
#nullable restore
#else
        public string ActivateWebhookUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deactivate a webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeactivateWebhookUrl { get; set; }
#nullable restore
#else
        public string DeactivateWebhookUrl { get; set; }
#endif
        /// <summary>Link to the [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationUrl { get; set; }
#nullable restore
#else
        public string OrganizationUrl { get; set; }
#endif
        /// <summary>Test a webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestWebhookUrl { get; set; }
#nullable restore
#else
        public string TestWebhookUrl { get; set; }
#endif
        /// <summary>A description of the webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookDescription { get; set; }
#nullable restore
#else
        public string WebhookDescription { get; set; }
#endif
        /// <summary>The callback URL of the webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookDestinationUrl { get; set; }
#nullable restore
#else
        public string WebhookDestinationUrl { get; set; }
#endif
        /// <summary>Link to the [webhook](#tag/Webhooks).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Webhooks.Item.WebhookGetResponse"/> and sets the default values.
        /// </summary>
        public WebhookGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Webhooks.Item.WebhookGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Webhooks.Item.WebhookGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Webhooks.Item.WebhookGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activate-webhook-url", n => { ActivateWebhookUrl = n.GetStringValue(); } },
                { "deactivate-webhook-url", n => { DeactivateWebhookUrl = n.GetStringValue(); } },
                { "organization-url", n => { OrganizationUrl = n.GetStringValue(); } },
                { "test-webhook-url", n => { TestWebhookUrl = n.GetStringValue(); } },
                { "webhook-description", n => { WebhookDescription = n.GetStringValue(); } },
                { "webhook-destination-url", n => { WebhookDestinationUrl = n.GetStringValue(); } },
                { "webhook-url", n => { WebhookUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activate-webhook-url", ActivateWebhookUrl);
            writer.WriteStringValue("deactivate-webhook-url", DeactivateWebhookUrl);
            writer.WriteStringValue("organization-url", OrganizationUrl);
            writer.WriteStringValue("test-webhook-url", TestWebhookUrl);
            writer.WriteStringValue("webhook-description", WebhookDescription);
            writer.WriteStringValue("webhook-destination-url", WebhookDestinationUrl);
            writer.WriteStringValue("webhook-url", WebhookUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
