// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Bank.Transactions.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Shows the [account balance](/docs/terms/account-balance).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_accountBalance? AccountBalance { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_accountBalance AccountBalance { get; set; }
#endif
        /// <summary>Link to the transaction resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountTransactionUrl { get; set; }
#nullable restore
#else
        public string AccountTransactionUrl { get; set; }
#endif
        /// <summary>Link to the bank account resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountUrl { get; set; }
#nullable restore
#else
        public string AccountUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Shows the account [balance change](/docs/terms/balance-change).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChange? BalanceChange { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChange BalanceChange { get; set; }
#endif
        /// <summary>Specifies the direction of a balance change.</summary>
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChangeDirection? BalanceChangeDirection { get; set; }
        /// <summary>This field is provided by the bank to help customers understand the nature of the transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>When the transaction actually takes effect on the account balance.</summary>
        public DateTimeOffset? EffectiveAt { get; set; }
        /// <summary>Link to the payment resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentUrl { get; set; }
#nullable restore
#else
        public string PaymentUrl { get; set; }
#endif
        /// <summary>Deprecated. Please use `processed-at` instead.</summary>
        public DateTimeOffset? PostDatetime { get; set; }
        /// <summary>When the transaction was entered into the account ledger.</summary>
        public DateTimeOffset? ProcessedAt { get; set; }
        /// <summary>This field is provided by the person or entity who made the payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>Specifies the origin of a balance change, for example a payment</summary>
        public global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_transactionOriginType? TransactionOriginType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse"/> and sets the default values.
        /// </summary>
        public TransactionGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-balance", n => { AccountBalance = n.GetObjectValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_accountBalance>(global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_accountBalance.CreateFromDiscriminatorValue); } },
                { "account-transaction-url", n => { AccountTransactionUrl = n.GetStringValue(); } },
                { "account-url", n => { AccountUrl = n.GetStringValue(); } },
                { "balance-change", n => { BalanceChange = n.GetObjectValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChange>(global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChange.CreateFromDiscriminatorValue); } },
                { "balance-change-direction", n => { BalanceChangeDirection = n.GetEnumValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChangeDirection>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "effective-at", n => { EffectiveAt = n.GetDateTimeOffsetValue(); } },
                { "payment-url", n => { PaymentUrl = n.GetStringValue(); } },
                { "post-datetime", n => { PostDatetime = n.GetDateTimeOffsetValue(); } },
                { "processed-at", n => { ProcessedAt = n.GetDateTimeOffsetValue(); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "transaction-origin-type", n => { TransactionOriginType = n.GetEnumValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_transactionOriginType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_accountBalance>("account-balance", AccountBalance);
            writer.WriteStringValue("account-transaction-url", AccountTransactionUrl);
            writer.WriteStringValue("account-url", AccountUrl);
            writer.WriteObjectValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChange>("balance-change", BalanceChange);
            writer.WriteEnumValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_balanceChangeDirection>("balance-change-direction", BalanceChangeDirection);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("effective-at", EffectiveAt);
            writer.WriteStringValue("payment-url", PaymentUrl);
            writer.WriteDateTimeOffsetValue("post-datetime", PostDatetime);
            writer.WriteDateTimeOffsetValue("processed-at", ProcessedAt);
            writer.WriteStringValue("reference", Reference);
            writer.WriteEnumValue<global::Griffin.Client.V0.Bank.Transactions.Item.TransactionGetResponse_transactionOriginType>("transaction-origin-type", TransactionOriginType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
