// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Bank.Products.Item.Accounts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountsPostResponse_availableBalance_currency
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        GBP,
        #pragma warning restore CS1591
    }
}
