// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Bank.Products.Item.Accounts
{
    /// <summary>Specifies the type of client money account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountsPostResponse_clientMoneyType
    {
        [EnumMember(Value = "designated-client-fund")]
        #pragma warning disable CS1591
        DesignatedClientFund,
        #pragma warning restore CS1591
        [EnumMember(Value = "designated-client-money")]
        #pragma warning disable CS1591
        DesignatedClientMoney,
        #pragma warning restore CS1591
        [EnumMember(Value = "general-client-money")]
        #pragma warning disable CS1591
        GeneralClientMoney,
        #pragma warning restore CS1591
    }
}
