// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Bank.Products.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BankProductGetResponse_bankAccountProductClass
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "savings")]
        #pragma warning disable CS1591
        Savings,
        #pragma warning restore CS1591
        [EnumMember(Value = "safeguarding")]
        #pragma warning disable CS1591
        Safeguarding,
        #pragma warning restore CS1591
        [EnumMember(Value = "client-money")]
        #pragma warning disable CS1591
        ClientMoney,
        #pragma warning restore CS1591
        [EnumMember(Value = "operational")]
        #pragma warning disable CS1591
        Operational,
        #pragma warning restore CS1591
        [EnumMember(Value = "embedded")]
        #pragma warning disable CS1591
        Embedded,
        #pragma warning restore CS1591
    }
}
