// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\bank\accounts\{bank-account-id}\transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}/transactions{?filter%5Bprocessed%2Dat%5D%5Bgt%5D*,filter%5Bprocessed%2Dat%5D%5Bgte%5D*,filter%5Bprocessed%2Dat%5D%5Blt%5D*,filter%5Bprocessed%2Dat%5D%5Blte%5D*,include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}/transactions{?filter%5Bprocessed%2Dat%5D%5Bgt%5D*,filter%5Bprocessed%2Dat%5D%5Bgte%5D*,filter%5Bprocessed%2Dat%5D%5Blt%5D*,filter%5Bprocessed%2Dat%5D%5Blte%5D*,include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists transactions on a bank account. Use an `Accept: application/vnd.griffin+xero-csv` header to receive transactions in a CSV format suitable for importing into [Xero](https://central.xero.com/s/article/Import-a-CSV-bank-statement). This endpoint will only return CSV files with up to 100,000 rows to match the [Xero import limit](https://central.xero.com/s/article/Import-a-CSV-bank-statement#Preparethedatainthefile:~:text=more%20than%20100%2C000%20rows). To ensure that no transactions are missing from the CSV export, specify a time period that contains fewer than 100,000 transactions.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsGetResponse?> GetAsTransactionsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsGetResponse> GetAsTransactionsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsGetResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists transactions on a bank account. Use an `Accept: application/vnd.griffin+xero-csv` header to receive transactions in a CSV format suitable for importing into [Xero](https://central.xero.com/s/article/Import-a-CSV-bank-statement). This endpoint will only return CSV files with up to 100,000 rows to match the [Xero import limit](https://central.xero.com/s/article/Import-a-CSV-bank-statement#Preparethedatainthefile:~:text=more%20than%20100%2C000%20rows). To ensure that no transactions are missing from the CSV export, specify a time period that contains fewer than 100,000 transactions.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsTransactionsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsResponse?> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsResponse> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists transactions on a bank account. Use an `Accept: application/vnd.griffin+xero-csv` header to receive transactions in a CSV format suitable for importing into [Xero](https://central.xero.com/s/article/Import-a-CSV-bank-statement). This endpoint will only return CSV files with up to 100,000 rows to match the [Xero import limit](https://central.xero.com/s/article/Import-a-CSV-bank-statement#Preparethedatainthefile:~:text=more%20than%20100%2C000%20rows). To ensure that no transactions are missing from the CSV export, specify a time period that contains fewer than 100,000 transactions.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists transactions on a bank account. Use an `Accept: application/vnd.griffin+xero-csv` header to receive transactions in a CSV format suitable for importing into [Xero](https://central.xero.com/s/article/Import-a-CSV-bank-statement). This endpoint will only return CSV files with up to 100,000 rows to match the [Xero import limit](https://central.xero.com/s/article/Import-a-CSV-bank-statement#Preparethedatainthefile:~:text=more%20than%20100%2C000%20rows). To ensure that no transactions are missing from the CSV export, specify a time period that contains fewer than 100,000 transactions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Return only transactions processed after the given timestamp.</summary>
            [QueryParameter("filter%5Bprocessed%2Dat%5D%5Bgt%5D")]
            public DateTimeOffset? FilterprocessedAtgt { get; set; }
            /// <summary>Return only transactions processed at or after the given timestamp.</summary>
            [QueryParameter("filter%5Bprocessed%2Dat%5D%5Bgte%5D")]
            public DateTimeOffset? FilterprocessedAtgte { get; set; }
            /// <summary>Return only transactions processed before the given timestamp.</summary>
            [QueryParameter("filter%5Bprocessed%2Dat%5D%5Blt%5D")]
            public DateTimeOffset? FilterprocessedAtlt { get; set; }
            /// <summary>Return only transactions processed at or before the given timestamp.</summary>
            [QueryParameter("filter%5Bprocessed%2Dat%5D%5Blte%5D")]
            public DateTimeOffset? FilterprocessedAtlte { get; set; }
            /// <summary>For each transaction returned, include its payment (if one exists) in the response under the `included` attribute.</summary>
            [Obsolete("This property is deprecated, use IncludeAsGetIncludeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
            /// <summary>For each transaction returned, include its payment (if one exists) in the response under the `included` attribute.</summary>
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.GetIncludeQueryParameterType? IncludeAsGetIncludeQueryParameterType { get; set; }
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public byte[]? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public byte[] Pageafter { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bbefore%5D")]
            public byte[]? Pagebefore { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bbefore%5D")]
            public byte[] Pagebefore { get; set; }
#endif
            [QueryParameter("page%5Bsize%5D")]
            public long? Pagesize { get; set; }
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("sort")]
            public global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
