// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Claims
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\legal-persons\{legal-person-id}\claims
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClaimsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClaimsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/legal-persons/{legal%2Dperson%2Did}/claims{?filter%5Bverification%2Dstatus%5D%5Beq%5D*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClaimsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/legal-persons/{legal%2Dperson%2Did}/claims{?filter%5Bverification%2Dstatus%5D%5Beq%5D*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Yields a list of all current claims about this Legal Person.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsGetResponse?> GetAsClaimsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsGetResponse> GetAsClaimsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsGetResponse>(requestInfo, global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Yields a list of all current claims about this Legal Person.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsClaimsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse?> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse>(requestInfo, global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new claim about a Legal Person.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostResponse?> PostAsClaimsPostResponseAsync(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostResponse> PostAsClaimsPostResponseAsync(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostResponse>(requestInfo, global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new claim about a Legal Person.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsClaimsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse?> PostAsync(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse> PostAsync(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse>(requestInfo, global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Yields a list of all current claims about this Legal Person.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new claim about a Legal Person.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Yields a list of all current claims about this Legal Person.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClaimsRequestBuilderGetQueryParameters 
        {
            /// <summary>The verification-status of a claim changes from `&quot;unverified&quot;` to `&quot;verified&quot;` when it has successfully been used in a verification as part of an accepted application. Claims of errored or declined applications are `&quot;unverified&quot;`.</summary>
            [Obsolete("This property is deprecated, use FilterverificationStatuseqAsGetFilterVerificationStatusEqQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bverification%2Dstatus%5D%5Beq%5D")]
            public string? FilterverificationStatuseq { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bverification%2Dstatus%5D%5Beq%5D")]
            public string FilterverificationStatuseq { get; set; }
#endif
            /// <summary>The verification-status of a claim changes from `&quot;unverified&quot;` to `&quot;verified&quot;` when it has successfully been used in a verification as part of an accepted application. Claims of errored or declined applications are `&quot;unverified&quot;`.</summary>
            [QueryParameter("filter%5Bverification%2Dstatus%5D%5Beq%5D")]
            public global::Griffin.Client.V0.LegalPersons.Item.Claims.GetFilterVerificationStatusEqQueryParameterType? FilterverificationStatuseqAsGetFilterVerificationStatusEqQueryParameterType { get; set; }
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public byte[]? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public byte[] Pageafter { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bbefore%5D")]
            public byte[]? Pagebefore { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bbefore%5D")]
            public byte[] Pagebefore { get; set; }
#endif
            [QueryParameter("page%5Bsize%5D")]
            public long? Pagesize { get; set; }
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("sort")]
            public global::Griffin.Client.V0.LegalPersons.Item.Claims.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClaimsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.LegalPersons.Item.Claims.ClaimsRequestBuilder.ClaimsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClaimsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
