// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BankAccountGetResponse_bankAddresses_bankIdCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gbdsc")]
        #pragma warning disable CS1591
        Gbdsc,
        #pragma warning restore CS1591
    }
}
