// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Bank.Accounts.Item.Actions;
using Griffin.Client.V0.Bank.Accounts.Item.Admissions;
using Griffin.Client.V0.Bank.Accounts.Item.Membership;
using Griffin.Client.V0.Bank.Accounts.Item.MembershipUpdates;
using Griffin.Client.V0.Bank.Accounts.Item.Payments;
using Griffin.Client.V0.Bank.Accounts.Item.Submissions;
using Griffin.Client.V0.Bank.Accounts.Item.Transactions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\bank\accounts\{bank-account-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BankAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The admissions property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Admissions.AdmissionsRequestBuilder Admissions
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Admissions.AdmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membership property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder Membership
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membershipUpdates property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.MembershipUpdates.MembershipUpdatesRequestBuilder MembershipUpdates
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.MembershipUpdates.MembershipUpdatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submissions property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Griffin.Client.V0.Bank.Accounts.Item.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch a bank account
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountGetResponse?> GetAsBankAccountGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountGetResponse> GetAsBankAccountGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountGetResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch a bank account
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsBankAccountGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a bank account
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchResponse?> PatchAsBankAccountPatchResponseAsync(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchResponse> PatchAsBankAccountPatchResponseAsync(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a bank account
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PatchAsBankAccountPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse?> PatchAsync(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse> PatchAsync(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch a bank account
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a bank account
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Bank.Accounts.Item.BankAccountItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BankAccountItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BankAccountItemRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
