// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item.Membership
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "latest-risk-rating")]
        #pragma warning disable CS1591
        LatestRiskRating,
        #pragma warning restore CS1591
        [EnumMember(Value = "legal-person")]
        #pragma warning disable CS1591
        LegalPerson,
        #pragma warning restore CS1591
        [EnumMember(Value = "latest-verification")]
        #pragma warning disable CS1591
        LatestVerification,
        #pragma warning restore CS1591
    }
}
