// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item.Membership
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\bank\accounts\{bank-account-id}\membership
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembershipRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}/membership{?include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/bank/accounts/{bank%2Daccount%2Did}/membership{?include*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// List legal persons in a pooled account membership
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse?> GetAsMembershipGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse> GetAsMembershipGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List legal persons in a pooled account membership
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsMembershipGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipResponse?> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipResponse> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipResponse>(requestInfo, global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List legal persons in a pooled account membership
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List legal persons in a pooled account membership
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MembershipRequestBuilderGetQueryParameters 
        {
            /// <summary>For each member returned, include its legal person details, latest verification (if one exists), and/or latest risk rating (if one exists) in the response under the `included` attribute.</summary>
            [Obsolete("This property is deprecated, use IncludeAsGetIncludeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string[] Include { get; set; }
#endif
            /// <summary>For each member returned, include its legal person details, latest verification (if one exists), and/or latest risk rating (if one exists) in the response under the `included` attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.GetIncludeQueryParameterType[]? IncludeAsGetIncludeQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.GetIncludeQueryParameterType[] IncludeAsGetIncludeQueryParameterType { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public byte[]? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public byte[] Pageafter { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bbefore%5D")]
            public byte[]? Pagebefore { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bbefore%5D")]
            public byte[] Pagebefore { get; set; }
#endif
            [QueryParameter("page%5Bsize%5D")]
            public long? Pagesize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MembershipRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipRequestBuilder.MembershipRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
