// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Bank.Accounts.Item.Membership
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MembershipGetResponse_included_riskRatingEntries : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A contextual link to the [legal person](#tag/Legal-persons).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalPersonUrl { get; set; }
#nullable restore
#else
        public string LegalPersonUrl { get; set; }
#endif
        /// <summary>User that triggered this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_manuallyCreatedBy? ManuallyCreatedBy { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_manuallyCreatedBy ManuallyCreatedBy { get; set; }
#endif
        /// <summary>Rationale for overriding the risk rating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The previousRiskRating property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_previousRiskRating? PreviousRiskRating { get; set; }
        /// <summary>The riskRating property</summary>
        public global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_riskRating? RiskRating { get; set; }
        /// <summary>A contextual link to the risk rating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RiskRatingUrl { get; set; }
#nullable restore
#else
        public string RiskRatingUrl { get; set; }
#endif
        /// <summary>A link to the [verification](#tag/Verifications).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerificationUrl { get; set; }
#nullable restore
#else
        public string VerificationUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries"/> and sets the default values.
        /// </summary>
        public MembershipGetResponse_included_riskRatingEntries()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "legal-person-url", n => { LegalPersonUrl = n.GetStringValue(); } },
                { "manually-created-by", n => { ManuallyCreatedBy = n.GetObjectValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_manuallyCreatedBy>(global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_manuallyCreatedBy.CreateFromDiscriminatorValue); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "previous-risk-rating", n => { PreviousRiskRating = n.GetEnumValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_previousRiskRating>(); } },
                { "risk-rating", n => { RiskRating = n.GetEnumValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_riskRating>(); } },
                { "risk-rating-url", n => { RiskRatingUrl = n.GetStringValue(); } },
                { "verification-url", n => { VerificationUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("legal-person-url", LegalPersonUrl);
            writer.WriteObjectValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_manuallyCreatedBy>("manually-created-by", ManuallyCreatedBy);
            writer.WriteStringValue("notes", Notes);
            writer.WriteEnumValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_previousRiskRating>("previous-risk-rating", PreviousRiskRating);
            writer.WriteEnumValue<global::Griffin.Client.V0.Bank.Accounts.Item.Membership.MembershipGetResponse_included_riskRatingEntries_riskRating>("risk-rating", RiskRating);
            writer.WriteStringValue("risk-rating-url", RiskRatingUrl);
            writer.WriteStringValue("verification-url", VerificationUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
