// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Bank.Payees
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cop-requests")]
        #pragma warning disable CS1591
        CopRequests,
        #pragma warning restore CS1591
    }
}
