// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Bank.Payees
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PayeesGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Present only when the request uses the `include` parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Included { get; set; }
#nullable restore
#else
        public UntypedNode Included { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_links? Links { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_links Links { get; set; }
#endif
        /// <summary>The payees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_payees>? Payees { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_payees> Payees { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse"/> and sets the default values.
        /// </summary>
        public PayeesGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "included", n => { Included = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetObjectValue<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_links>(global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_links.CreateFromDiscriminatorValue); } },
                { "payees", n => { Payees = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_payees>(global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_payees.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("included", Included);
            writer.WriteObjectValue<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_links>("links", Links);
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.LegalPersons.Item.Bank.Payees.PayeesGetResponse_payees>("payees", Payees);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
