// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.CompaniesHouse.Companies.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.CompaniesHouse.Companies
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\companies-house\companies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompaniesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Griffin.Client.v0.companiesHouse.companies.item collection</summary>
        /// <param name="position">UK Companies House company number</param>
        /// <returns>A <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberItemRequestBuilder"/></returns>
        public global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("company%2Dnumber", position);
                return new global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/companies-house/companies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/companies-house/companies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
