// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Admissions;
using Griffin.Client.V0.ApiKeys;
using Griffin.Client.V0.Bank;
using Griffin.Client.V0.Claims;
using Griffin.Client.V0.CompaniesHouse;
using Griffin.Client.V0.CopRequest;
using Griffin.Client.V0.Events;
using Griffin.Client.V0.IndexNamespace;
using Griffin.Client.V0.LegalPersons;
using Griffin.Client.V0.Memberships;
using Griffin.Client.V0.Onboarding;
using Griffin.Client.V0.Organizations;
using Griffin.Client.V0.Payees;
using Griffin.Client.V0.Payments;
using Griffin.Client.V0.Ping;
using Griffin.Client.V0.Roles;
using Griffin.Client.V0.Security;
using Griffin.Client.V0.Simulation;
using Griffin.Client.V0.Submissions;
using Griffin.Client.V0.Users;
using Griffin.Client.V0.Verifications;
using Griffin.Client.V0.Webhooks;
using Griffin.Client.V0.Workflows;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0
{
    /// <summary>
    /// Builds and executes requests for operations under \v0
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V0RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The admissions property</summary>
        public global::Griffin.Client.V0.Admissions.AdmissionsRequestBuilder Admissions
        {
            get => new global::Griffin.Client.V0.Admissions.AdmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apiKeys property</summary>
        public global::Griffin.Client.V0.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::Griffin.Client.V0.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bank property</summary>
        public global::Griffin.Client.V0.Bank.BankRequestBuilder Bank
        {
            get => new global::Griffin.Client.V0.Bank.BankRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The claims property</summary>
        public global::Griffin.Client.V0.Claims.ClaimsRequestBuilder Claims
        {
            get => new global::Griffin.Client.V0.Claims.ClaimsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companiesHouse property</summary>
        public global::Griffin.Client.V0.CompaniesHouse.CompaniesHouseRequestBuilder CompaniesHouse
        {
            get => new global::Griffin.Client.V0.CompaniesHouse.CompaniesHouseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The copRequest property</summary>
        public global::Griffin.Client.V0.CopRequest.CopRequestRequestBuilder CopRequest
        {
            get => new global::Griffin.Client.V0.CopRequest.CopRequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Griffin.Client.V0.Events.EventsRequestBuilder Events
        {
            get => new global::Griffin.Client.V0.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The index property</summary>
        public global::Griffin.Client.V0.IndexNamespace.IndexRequestBuilder Index
        {
            get => new global::Griffin.Client.V0.IndexNamespace.IndexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The legalPersons property</summary>
        public global::Griffin.Client.V0.LegalPersons.LegalPersonsRequestBuilder LegalPersons
        {
            get => new global::Griffin.Client.V0.LegalPersons.LegalPersonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memberships property</summary>
        public global::Griffin.Client.V0.Memberships.MembershipsRequestBuilder Memberships
        {
            get => new global::Griffin.Client.V0.Memberships.MembershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The onboarding property</summary>
        public global::Griffin.Client.V0.Onboarding.OnboardingRequestBuilder Onboarding
        {
            get => new global::Griffin.Client.V0.Onboarding.OnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Griffin.Client.V0.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Griffin.Client.V0.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payees property</summary>
        public global::Griffin.Client.V0.Payees.PayeesRequestBuilder Payees
        {
            get => new global::Griffin.Client.V0.Payees.PayeesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::Griffin.Client.V0.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Griffin.Client.V0.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::Griffin.Client.V0.Ping.PingRequestBuilder Ping
        {
            get => new global::Griffin.Client.V0.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Griffin.Client.V0.Roles.RolesRequestBuilder Roles
        {
            get => new global::Griffin.Client.V0.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The security property</summary>
        public global::Griffin.Client.V0.Security.SecurityRequestBuilder Security
        {
            get => new global::Griffin.Client.V0.Security.SecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulation property</summary>
        public global::Griffin.Client.V0.Simulation.SimulationRequestBuilder Simulation
        {
            get => new global::Griffin.Client.V0.Simulation.SimulationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submissions property</summary>
        public global::Griffin.Client.V0.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::Griffin.Client.V0.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Griffin.Client.V0.Users.UsersRequestBuilder Users
        {
            get => new global::Griffin.Client.V0.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verifications property</summary>
        public global::Griffin.Client.V0.Verifications.VerificationsRequestBuilder Verifications
        {
            get => new global::Griffin.Client.V0.Verifications.VerificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Griffin.Client.V0.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Griffin.Client.V0.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Griffin.Client.V0.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Griffin.Client.V0.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
