// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Payees.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PayeeGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The name of the [account holder](/docs/terms/account-holder).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountHolder { get; set; }
#nullable restore
#else
        public string AccountHolder { get; set; }
#endif
        /// <summary>Must be a UK account number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Link to the bank account resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountUrl { get; set; }
#nullable restore
#else
        public string AccountUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Must be a UK Sort Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankId { get; set; }
#nullable restore
#else
        public string BankId { get; set; }
#endif
        /// <summary>Link to a [CoP request](#tag/Confirmation-of-payee).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CopRequestUrl { get; set; }
#nullable restore
#else
        public string CopRequestUrl { get; set; }
#endif
        /// <summary>ISO 3166-1 alpha-2 two-letter country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CountryCode { get; set; }
#nullable restore
#else
        public UntypedNode CountryCode { get; set; }
#endif
        /// <summary>ISO 8601 formatted date-time.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A contextual link to the [legal person](#tag/Legal-persons).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalPersonUrl { get; set; }
#nullable restore
#else
        public string LegalPersonUrl { get; set; }
#endif
        /// <summary>The status of the payee; you can only make payments to active payees.</summary>
        public global::Griffin.Client.V0.Payees.Item.PayeeGetResponse_payeeStatus? PayeeStatus { get; set; }
        /// <summary>Link to the [payee](#tag/Payees).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayeeUrl { get; set; }
#nullable restore
#else
        public string PayeeUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Payees.Item.PayeeGetResponse"/> and sets the default values.
        /// </summary>
        public PayeeGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Payees.Item.PayeeGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Payees.Item.PayeeGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Payees.Item.PayeeGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-holder", n => { AccountHolder = n.GetStringValue(); } },
                { "account-number", n => { AccountNumber = n.GetStringValue(); } },
                { "account-url", n => { AccountUrl = n.GetStringValue(); } },
                { "bank-id", n => { BankId = n.GetStringValue(); } },
                { "cop-request-url", n => { CopRequestUrl = n.GetStringValue(); } },
                { "country-code", n => { CountryCode = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "legal-person-url", n => { LegalPersonUrl = n.GetStringValue(); } },
                { "payee-status", n => { PayeeStatus = n.GetEnumValue<global::Griffin.Client.V0.Payees.Item.PayeeGetResponse_payeeStatus>(); } },
                { "payee-url", n => { PayeeUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account-holder", AccountHolder);
            writer.WriteStringValue("account-number", AccountNumber);
            writer.WriteStringValue("account-url", AccountUrl);
            writer.WriteStringValue("bank-id", BankId);
            writer.WriteStringValue("cop-request-url", CopRequestUrl);
            writer.WriteObjectValue<UntypedNode>("country-code", CountryCode);
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteStringValue("legal-person-url", LegalPersonUrl);
            writer.WriteEnumValue<global::Griffin.Client.V0.Payees.Item.PayeeGetResponse_payeeStatus>("payee-status", PayeeStatus);
            writer.WriteStringValue("payee-url", PayeeUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
