// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Payees.Item
{
    /// <summary>The status of the payee; you can only make payments to active payees.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PayeePatchResponse_payeeStatus
    {
        [EnumMember(Value = "deactivated")]
        #pragma warning disable CS1591
        Deactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
    }
}
