// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.CompaniesHouse.Companies.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CompanyNumberGetResponse_corporationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "private-limited-guarant-nsc-limited-exemption")]
        #pragma warning disable CS1591
        PrivateLimitedGuarantNscLimitedExemption,
        #pragma warning restore CS1591
        [EnumMember(Value = "eeig")]
        #pragma warning disable CS1591
        Eeig,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-limited-shares-section-30-exemption")]
        #pragma warning disable CS1591
        PrivateLimitedSharesSection30Exemption,
        #pragma warning restore CS1591
        [EnumMember(Value = "limited-partnership")]
        #pragma warning disable CS1591
        LimitedPartnership,
        #pragma warning restore CS1591
        [EnumMember(Value = "royal-charter")]
        #pragma warning disable CS1591
        RoyalCharter,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-unlimited-nsc")]
        #pragma warning disable CS1591
        PrivateUnlimitedNsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "old-public-company")]
        #pragma warning disable CS1591
        OldPublicCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "investment-company-with-variable-capital")]
        #pragma warning disable CS1591
        InvestmentCompanyWithVariableCapital,
        #pragma warning restore CS1591
        [EnumMember(Value = "other-company-type")]
        #pragma warning disable CS1591
        OtherCompanyType,
        #pragma warning restore CS1591
        [EnumMember(Value = "converted-or-closed")]
        #pragma warning disable CS1591
        ConvertedOrClosed,
        #pragma warning restore CS1591
        [EnumMember(Value = "protected-cell-company")]
        #pragma warning disable CS1591
        ProtectedCellCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-limited-guarant-nsc")]
        #pragma warning disable CS1591
        PrivateLimitedGuarantNsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "scottish-charitable-incorporated-organisation")]
        #pragma warning disable CS1591
        ScottishCharitableIncorporatedOrganisation,
        #pragma warning restore CS1591
        [EnumMember(Value = "industrial-and-provident-society")]
        #pragma warning disable CS1591
        IndustrialAndProvidentSociety,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered-society-non-jurisdictional")]
        #pragma warning disable CS1591
        RegisteredSocietyNonJurisdictional,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-unlimited")]
        #pragma warning disable CS1591
        PrivateUnlimited,
        #pragma warning restore CS1591
        [EnumMember(Value = "further-education-or-sixth-form-college-corporation")]
        #pragma warning disable CS1591
        FurtherEducationOrSixthFormCollegeCorporation,
        #pragma warning restore CS1591
        [EnumMember(Value = "limited-liability-partnership")]
        #pragma warning disable CS1591
        LimitedLiabilityPartnership,
        #pragma warning restore CS1591
        [EnumMember(Value = "assurance-company")]
        #pragma warning disable CS1591
        AssuranceCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "northern-ireland-other")]
        #pragma warning disable CS1591
        NorthernIrelandOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "charitable-incorporated-organisation")]
        #pragma warning disable CS1591
        CharitableIncorporatedOrganisation,
        #pragma warning restore CS1591
        [EnumMember(Value = "oversea-company")]
        #pragma warning disable CS1591
        OverseaCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "icvc-securities")]
        #pragma warning disable CS1591
        IcvcSecurities,
        #pragma warning restore CS1591
        [EnumMember(Value = "uk-establishment")]
        #pragma warning disable CS1591
        UkEstablishment,
        #pragma warning restore CS1591
        [EnumMember(Value = "unregistered-company")]
        #pragma warning disable CS1591
        UnregisteredCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "icvc-warrant")]
        #pragma warning disable CS1591
        IcvcWarrant,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered-overseas-entity")]
        #pragma warning disable CS1591
        RegisteredOverseasEntity,
        #pragma warning restore CS1591
        [EnumMember(Value = "public-limited-company")]
        #pragma warning disable CS1591
        PublicLimitedCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-limited-company")]
        #pragma warning disable CS1591
        PrivateLimitedCompany,
        #pragma warning restore CS1591
        [EnumMember(Value = "european-public-limited-liability-company-se")]
        #pragma warning disable CS1591
        EuropeanPublicLimitedLiabilityCompanySe,
        #pragma warning restore CS1591
        [EnumMember(Value = "private-unlimted-nsc")]
        #pragma warning disable CS1591
        PrivateUnlimtedNsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "northern-ireland")]
        #pragma warning disable CS1591
        NorthernIreland,
        #pragma warning restore CS1591
        [EnumMember(Value = "icvc-umbrella")]
        #pragma warning disable CS1591
        IcvcUmbrella,
        #pragma warning restore CS1591
        [EnumMember(Value = "scottish-partnership")]
        #pragma warning disable CS1591
        ScottishPartnership,
        #pragma warning restore CS1591
    }
}
