// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.CompaniesHouse.Companies.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CompanyNumberGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountsOverdue property</summary>
        public bool? AccountsOverdue { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The companyAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyAddress? CompanyAddress { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyAddress CompanyAddress { get; set; }
#endif
        /// <summary>The companyStatus property</summary>
        public global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyStatus? CompanyStatus { get; set; }
        /// <summary>The confirmationStatementOverdue property</summary>
        public bool? ConfirmationStatementOverdue { get; set; }
        /// <summary>The corporationType property</summary>
        public global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_corporationType? CorporationType { get; set; }
        /// <summary>ISO 8601 formatted date.</summary>
        public Date? DateOfIncorporation { get; set; }
        /// <summary>ISO 8601 formatted date.</summary>
        public Date? DateOfLatestAccounts { get; set; }
        /// <summary>ISO 8601 formatted date.</summary>
        public Date? DateOfLatestConfirmationStatement { get; set; }
        /// <summary>The directors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors>? Directors { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors> Directors { get; set; }
#endif
        /// <summary>The entityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityName { get; set; }
#nullable restore
#else
        public string EntityName { get; set; }
#endif
        /// <summary>The entity number assigned by the local register. For UK companies that&apos;s the Companies House company number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityRegistrationNumber { get; set; }
#nullable restore
#else
        public string EntityRegistrationNumber { get; set; }
#endif
        /// <summary>The personsWithSignificantControl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_personsWithSignificantControl>? PersonsWithSignificantControl { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_personsWithSignificantControl> PersonsWithSignificantControl { get; set; }
#endif
        /// <summary>The sicCodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SicCodes { get; set; }
#nullable restore
#else
        public List<string> SicCodes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse"/> and sets the default values.
        /// </summary>
        public CompanyNumberGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts-overdue", n => { AccountsOverdue = n.GetBoolValue(); } },
                { "company-address", n => { CompanyAddress = n.GetObjectValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyAddress>(global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyAddress.CreateFromDiscriminatorValue); } },
                { "company-status", n => { CompanyStatus = n.GetEnumValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyStatus>(); } },
                { "confirmation-statement-overdue", n => { ConfirmationStatementOverdue = n.GetBoolValue(); } },
                { "corporation-type", n => { CorporationType = n.GetEnumValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_corporationType>(); } },
                { "date-of-incorporation", n => { DateOfIncorporation = n.GetDateValue(); } },
                { "date-of-latest-accounts", n => { DateOfLatestAccounts = n.GetDateValue(); } },
                { "date-of-latest-confirmation-statement", n => { DateOfLatestConfirmationStatement = n.GetDateValue(); } },
                { "directors", n => { Directors = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors>(global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "entity-name", n => { EntityName = n.GetStringValue(); } },
                { "entity-registration-number", n => { EntityRegistrationNumber = n.GetStringValue(); } },
                { "persons-with-significant-control", n => { PersonsWithSignificantControl = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_personsWithSignificantControl>(global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_personsWithSignificantControl.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sic-codes", n => { SicCodes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("accounts-overdue", AccountsOverdue);
            writer.WriteObjectValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyAddress>("company-address", CompanyAddress);
            writer.WriteEnumValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_companyStatus>("company-status", CompanyStatus);
            writer.WriteBoolValue("confirmation-statement-overdue", ConfirmationStatementOverdue);
            writer.WriteEnumValue<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_corporationType>("corporation-type", CorporationType);
            writer.WriteDateValue("date-of-incorporation", DateOfIncorporation);
            writer.WriteDateValue("date-of-latest-accounts", DateOfLatestAccounts);
            writer.WriteDateValue("date-of-latest-confirmation-statement", DateOfLatestConfirmationStatement);
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors>("directors", Directors);
            writer.WriteStringValue("entity-name", EntityName);
            writer.WriteStringValue("entity-registration-number", EntityRegistrationNumber);
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_personsWithSignificantControl>("persons-with-significant-control", PersonsWithSignificantControl);
            writer.WriteCollectionOfPrimitiveValues<string>("sic-codes", SicCodes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
