// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.CompaniesHouse.Companies.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CompanyNumberGetResponse_directors : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL of the entity in Companies House</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompaniesHouseUrl { get; set; }
#nullable restore
#else
        public string CompaniesHouseUrl { get; set; }
#endif
        /// <summary>The dayOfBirth property</summary>
        public long? DayOfBirth { get; set; }
        /// <summary>ISO 8601 formatted date.</summary>
        public Date? DirectorAppointedOn { get; set; }
        /// <summary>The directorOccupation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DirectorOccupation { get; set; }
#nullable restore
#else
        public string DirectorOccupation { get; set; }
#endif
        /// <summary>A human readable label for an entity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The monthOfBirth property</summary>
        public long? MonthOfBirth { get; set; }
        /// <summary>The yearOfBirth property</summary>
        public long? YearOfBirth { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors"/> and sets the default values.
        /// </summary>
        public CompanyNumberGetResponse_directors()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.CompaniesHouse.Companies.Item.CompanyNumberGetResponse_directors();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "companies-house-url", n => { CompaniesHouseUrl = n.GetStringValue(); } },
                { "day-of-birth", n => { DayOfBirth = n.GetLongValue(); } },
                { "director-appointed-on", n => { DirectorAppointedOn = n.GetDateValue(); } },
                { "director-occupation", n => { DirectorOccupation = n.GetStringValue(); } },
                { "display-name", n => { DisplayName = n.GetStringValue(); } },
                { "month-of-birth", n => { MonthOfBirth = n.GetLongValue(); } },
                { "year-of-birth", n => { YearOfBirth = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("companies-house-url", CompaniesHouseUrl);
            writer.WriteLongValue("day-of-birth", DayOfBirth);
            writer.WriteDateValue("director-appointed-on", DirectorAppointedOn);
            writer.WriteStringValue("director-occupation", DirectorOccupation);
            writer.WriteStringValue("display-name", DisplayName);
            writer.WriteLongValue("month-of-birth", MonthOfBirth);
            writer.WriteLongValue("year-of-birth", YearOfBirth);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
