// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.CompaniesHouse.Companies.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CompanyNumberGetResponse_companyStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "dissolved")]
        #pragma warning disable CS1591
        Dissolved,
        #pragma warning restore CS1591
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "receivership")]
        #pragma warning disable CS1591
        Receivership,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered")]
        #pragma warning disable CS1591
        Registered,
        #pragma warning restore CS1591
        [EnumMember(Value = "removed")]
        #pragma warning disable CS1591
        Removed,
        #pragma warning restore CS1591
        [EnumMember(Value = "administration")]
        #pragma warning disable CS1591
        Administration,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
        [EnumMember(Value = "voluntary-arrangement")]
        #pragma warning disable CS1591
        VoluntaryArrangement,
        #pragma warning restore CS1591
        [EnumMember(Value = "liquidation")]
        #pragma warning disable CS1591
        Liquidation,
        #pragma warning restore CS1591
        [EnumMember(Value = "converted-closed")]
        #pragma warning disable CS1591
        ConvertedClosed,
        #pragma warning restore CS1591
        [EnumMember(Value = "insolvency-proceedings")]
        #pragma warning disable CS1591
        InsolvencyProceedings,
        #pragma warning restore CS1591
    }
}
