// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Memberships
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MembershipsGetResponse_memberships : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO 8601 formatted date-time.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Link to the assigned [roles](#tag/Roles) for this [membership](#tag/Memberships).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MembershipRolesUrl { get; set; }
#nullable restore
#else
        public string MembershipRolesUrl { get; set; }
#endif
        /// <summary>Link to the [membership](#tag/Memberships).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MembershipUrl { get; set; }
#nullable restore
#else
        public string MembershipUrl { get; set; }
#endif
        /// <summary>The organization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_organization? Organization { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_organization Organization { get; set; }
#endif
        /// <summary>Shows a collection of [roles](#tag/Roles).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_roles>? Roles { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_roles> Roles { get; set; }
#endif
        /// <summary>Shows the associated [user](#tag/Users).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_user? User { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships"/> and sets the default values.
        /// </summary>
        public MembershipsGetResponse_memberships()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "membership-roles-url", n => { MembershipRolesUrl = n.GetStringValue(); } },
                { "membership-url", n => { MembershipUrl = n.GetStringValue(); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_organization>(global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_organization.CreateFromDiscriminatorValue); } },
                { "roles", n => { Roles = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_roles>(global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_roles.CreateFromDiscriminatorValue)?.AsList(); } },
                { "user", n => { User = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_user>(global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteStringValue("membership-roles-url", MembershipRolesUrl);
            writer.WriteStringValue("membership-url", MembershipUrl);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_organization>("organization", Organization);
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_roles>("roles", Roles);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Memberships.MembershipsGetResponse_memberships_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
