// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.Bank.Accounts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFilterAccountStatusInQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "closing")]
        #pragma warning disable CS1591
        Closing,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
        [EnumMember(Value = "opening")]
        #pragma warning disable CS1591
        Opening,
        #pragma warning restore CS1591
    }
}
