// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.Events
{
    /// <summary>The type of webhook event. Usually has the form {resource}-{operation}, e.g. payment-updated</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventsGetResponse_events_eventType
    {
        [EnumMember(Value = "onboarding-application-updated")]
        #pragma warning disable CS1591
        OnboardingApplicationUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "decision-created")]
        #pragma warning disable CS1591
        DecisionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment-created")]
        #pragma warning disable CS1591
        PaymentCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction-created")]
        #pragma warning disable CS1591
        TransactionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification-updated")]
        #pragma warning disable CS1591
        VerificationUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "admission-updated")]
        #pragma warning disable CS1591
        AdmissionUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification-created")]
        #pragma warning disable CS1591
        VerificationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "account-status-updated")]
        #pragma warning disable CS1591
        AccountStatusUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "onboarding-application-created")]
        #pragma warning disable CS1591
        OnboardingApplicationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "submission-created")]
        #pragma warning disable CS1591
        SubmissionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "test-event")]
        #pragma warning disable CS1591
        TestEvent,
        #pragma warning restore CS1591
        [EnumMember(Value = "admission-created")]
        #pragma warning disable CS1591
        AdmissionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification-resource-updated")]
        #pragma warning disable CS1591
        VerificationResourceUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "account-status-created")]
        #pragma warning disable CS1591
        AccountStatusCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification-resource-created")]
        #pragma warning disable CS1591
        VerificationResourceCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "submission-updated")]
        #pragma warning disable CS1591
        SubmissionUpdated,
        #pragma warning restore CS1591
    }
}
