// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Organizations.Item.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\organizations\{organization-id}\events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/events{?filter%5Bcreated%2Dat%5D%5Bgt%5D*,filter%5Bcreated%2Dat%5D%5Bgte%5D*,filter%5Bcreated%2Dat%5D%5Blt%5D*,filter%5Bcreated%2Dat%5D%5Blte%5D*,filter%5Bevent%2Dtype%5D%5Beq%5D*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/events{?filter%5Bcreated%2Dat%5D%5Bgt%5D*,filter%5Bcreated%2Dat%5D%5Bgte%5D*,filter%5Bcreated%2Dat%5D%5Blt%5D*,filter%5Bcreated%2Dat%5D%5Blte%5D*,filter%5Bevent%2Dtype%5D%5Beq%5D*,page%5Bafter%5D*,page%5Bbefore%5D*,page%5Bsize%5D*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// List all events for an organization
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse?> GetAsEventsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse> GetAsEventsGetResponseAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all events for an organization
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsEventsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.Events.EventsResponse?> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.Events.EventsResponse> GetAsync(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.Events.EventsResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.Events.EventsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all events for an organization
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all events for an organization
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetQueryParameters 
        {
            /// <summary>Return only events with a created-at greater than the given timestamp.</summary>
            [QueryParameter("filter%5Bcreated%2Dat%5D%5Bgt%5D")]
            public DateTimeOffset? FiltercreatedAtgt { get; set; }
            /// <summary>Return only events with a created-at greater than or equal to the given timestamp.</summary>
            [QueryParameter("filter%5Bcreated%2Dat%5D%5Bgte%5D")]
            public DateTimeOffset? FiltercreatedAtgte { get; set; }
            /// <summary>Return only events with a created-at less than the given timestamp.</summary>
            [QueryParameter("filter%5Bcreated%2Dat%5D%5Blt%5D")]
            public DateTimeOffset? FiltercreatedAtlt { get; set; }
            /// <summary>Return only events with a created-at less than or equal to the given timestamp.</summary>
            [QueryParameter("filter%5Bcreated%2Dat%5D%5Blte%5D")]
            public DateTimeOffset? FiltercreatedAtlte { get; set; }
            /// <summary>The type of webhook event. Usually has the form {resource}-{operation}, e.g. payment-updated</summary>
            [Obsolete("This property is deprecated, use FiltereventTypeeqAsGetFilterEventTypeEqQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bevent%2Dtype%5D%5Beq%5D")]
            public string? FiltereventTypeeq { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bevent%2Dtype%5D%5Beq%5D")]
            public string FiltereventTypeeq { get; set; }
#endif
            /// <summary>The type of webhook event. Usually has the form {resource}-{operation}, e.g. payment-updated</summary>
            [QueryParameter("filter%5Bevent%2Dtype%5D%5Beq%5D")]
            public global::Griffin.Client.V0.Organizations.Item.Events.GetFilterEventTypeEqQueryParameterType? FiltereventTypeeqAsGetFilterEventTypeEqQueryParameterType { get; set; }
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public byte[]? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public byte[] Pageafter { get; set; }
#endif
            /// <summary>A base64 encoded opaque string returned in paginated responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bbefore%5D")]
            public byte[]? Pagebefore { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bbefore%5D")]
            public byte[] Pagebefore { get; set; }
#endif
            [QueryParameter("page%5Bsize%5D")]
            public long? Pagesize { get; set; }
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("sort")]
            public global::Griffin.Client.V0.Organizations.Item.Events.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
