// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Events
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventsGetResponse_events : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO 8601 formatted date-time.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The eventPayload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventPayload? EventPayload { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventPayload EventPayload { get; set; }
#endif
        /// <summary>The type of webhook event. Usually has the form {resource}-{operation}, e.g. payment-updated</summary>
        public global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventType? EventType { get; set; }
        /// <summary>Link to the [event](#tag/Events).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventUrl { get; set; }
#nullable restore
#else
        public string EventUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events"/> and sets the default values.
        /// </summary>
        public EventsGetResponse_events()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "event-payload", n => { EventPayload = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventPayload>(global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventPayload.CreateFromDiscriminatorValue); } },
                { "event-type", n => { EventType = n.GetEnumValue<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventType>(); } },
                { "event-url", n => { EventUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventPayload>("event-payload", EventPayload);
            writer.WriteEnumValue<global::Griffin.Client.V0.Organizations.Item.Events.EventsGetResponse_events_eventType>("event-type", EventType);
            writer.WriteStringValue("event-url", EventUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
