// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Verifications
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationsPostResponse_riskRating
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "high-risk")]
        #pragma warning disable CS1591
        HighRisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "prohibited-risk")]
        #pragma warning disable CS1591
        ProhibitedRisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium-risk")]
        #pragma warning disable CS1591
        MediumRisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "low-risk")]
        #pragma warning disable CS1591
        LowRisk,
        #pragma warning restore CS1591
    }
}
