// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Payments
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentsGetResponse_payments_debtor : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The name of the [account holder](/docs/terms/account-holder).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountHolder { get; set; }
#nullable restore
#else
        public string AccountHolder { get; set; }
#endif
        /// <summary>Must be a UK account number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>The accountNumberCode property</summary>
        public global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_accountNumberCode? AccountNumberCode { get; set; }
        /// <summary>Link to the bank account resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountUrl { get; set; }
#nullable restore
#else
        public string AccountUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Must be a UK Sort Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankId { get; set; }
#nullable restore
#else
        public string BankId { get; set; }
#endif
        /// <summary>The bankIdCode property</summary>
        public global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_bankIdCode? BankIdCode { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor"/> and sets the default values.
        /// </summary>
        public PaymentsGetResponse_payments_debtor()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-holder", n => { AccountHolder = n.GetStringValue(); } },
                { "account-number", n => { AccountNumber = n.GetStringValue(); } },
                { "account-number-code", n => { AccountNumberCode = n.GetEnumValue<global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_accountNumberCode>(); } },
                { "account-url", n => { AccountUrl = n.GetStringValue(); } },
                { "bank-id", n => { BankId = n.GetStringValue(); } },
                { "bank-id-code", n => { BankIdCode = n.GetEnumValue<global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_bankIdCode>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account-holder", AccountHolder);
            writer.WriteStringValue("account-number", AccountNumber);
            writer.WriteEnumValue<global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_accountNumberCode>("account-number-code", AccountNumberCode);
            writer.WriteStringValue("account-url", AccountUrl);
            writer.WriteStringValue("bank-id", BankId);
            writer.WriteEnumValue<global::Griffin.Client.V0.Organizations.Item.Payments.PaymentsGetResponse_payments_debtor_bankIdCode>("bank-id-code", BankIdCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
