// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Admissions.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AdmissionGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Link to the bank account resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountUrl { get; set; }
#nullable restore
#else
        public string AccountUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The admissionSchemeInformation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionSchemeInformation? AdmissionSchemeInformation { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionSchemeInformation AdmissionSchemeInformation { get; set; }
#endif
        /// <summary>Specifies the progress of the inbound payment.</summary>
        public global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionStatus? AdmissionStatus { get; set; }
        /// <summary>The admissionUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdmissionUrl { get; set; }
#nullable restore
#else
        public string AdmissionUrl { get; set; }
#endif
        /// <summary>ISO 8601 formatted date-time.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The originalUniqueSchemeIdentifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalUniqueSchemeIdentifier { get; set; }
#nullable restore
#else
        public string OriginalUniqueSchemeIdentifier { get; set; }
#endif
        /// <summary>Link to the payment resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentUrl { get; set; }
#nullable restore
#else
        public string PaymentUrl { get; set; }
#endif
        /// <summary>The uniqueSchemeIdentifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniqueSchemeIdentifier { get; set; }
#nullable restore
#else
        public string UniqueSchemeIdentifier { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse"/> and sets the default values.
        /// </summary>
        public AdmissionGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-url", n => { AccountUrl = n.GetStringValue(); } },
                { "admission-scheme-information", n => { AdmissionSchemeInformation = n.GetObjectValue<global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionSchemeInformation>(global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionSchemeInformation.CreateFromDiscriminatorValue); } },
                { "admission-status", n => { AdmissionStatus = n.GetEnumValue<global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionStatus>(); } },
                { "admission-url", n => { AdmissionUrl = n.GetStringValue(); } },
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "original-unique-scheme-identifier", n => { OriginalUniqueSchemeIdentifier = n.GetStringValue(); } },
                { "payment-url", n => { PaymentUrl = n.GetStringValue(); } },
                { "unique-scheme-identifier", n => { UniqueSchemeIdentifier = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account-url", AccountUrl);
            writer.WriteObjectValue<global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionSchemeInformation>("admission-scheme-information", AdmissionSchemeInformation);
            writer.WriteEnumValue<global::Griffin.Client.V0.Admissions.Item.AdmissionGetResponse_admissionStatus>("admission-status", AdmissionStatus);
            writer.WriteStringValue("admission-url", AdmissionUrl);
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteStringValue("original-unique-scheme-identifier", OriginalUniqueSchemeIdentifier);
            writer.WriteStringValue("payment-url", PaymentUrl);
            writer.WriteStringValue("unique-scheme-identifier", UniqueSchemeIdentifier);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
