// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Onboarding.Applications
{
    [Obsolete("This class is obsolete. Use ApplicationsPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationsResponse : global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsResponse();
        }
    }
}
#pragma warning restore CS0618
