// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Onboarding.Applications
{
    /// <summary>
    /// The relationship with the subject profile. Choose at least one of the subject associations.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplicationsPostRequestBody_relatedProfiles_subjectAssociation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The director property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_director? Director { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_director Director { get; set; }
#endif
        /// <summary>The psc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_psc? Psc { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_psc Psc { get; set; }
#endif
        /// <summary>The seniorManager property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_seniorManager? SeniorManager { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_seniorManager SeniorManager { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation"/> and sets the default values.
        /// </summary>
        public ApplicationsPostRequestBody_relatedProfiles_subjectAssociation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "director", n => { Director = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_director>(global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_director.CreateFromDiscriminatorValue); } },
                { "psc", n => { Psc = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_psc>(global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_psc.CreateFromDiscriminatorValue); } },
                { "senior-manager", n => { SeniorManager = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_seniorManager>(global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_seniorManager.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_director>("director", Director);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_psc>("psc", Psc);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsPostRequestBody_relatedProfiles_subjectAssociation_seniorManager>("senior-manager", SeniorManager);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
