// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CopSimulationTypePostResponse_copResponse_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "unverified")]
        #pragma warning disable CS1591
        Unverified,
        #pragma warning restore CS1591
    }
}
