// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CopSimulationTypePostResponse_account_accountClassification
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
    }
}
