// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\simulation\organizations\{organization-id}\cop-request\simulate\{cop-simulation-type}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopSimulationTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopSimulationTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request/simulate/{cop%2Dsimulation%2Dtype}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopSimulationTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request/simulate/{cop%2Dsimulation%2Dtype}", rawUrl)
        {
        }
        /// <summary>
        /// Simulate the creation of a CoP Request. Note: This is an alpha API and may change anytime.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostResponse?> PostAsCopSimulationTypePostResponseAsync(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostResponse> PostAsCopSimulationTypePostResponseAsync(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostResponse>(requestInfo, global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Simulate the creation of a CoP Request. Note: This is an alpha API and may change anytime.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsCopSimulationTypePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeResponse?> PostAsync(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeResponse> PostAsync(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeResponse>(requestInfo, global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Simulate the creation of a CoP Request. Note: This is an alpha API and may change anytime.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CopSimulationTypeItemRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
