// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\simulation\organizations\{organization-id}\cop-request\simulate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Griffin.Client.v0.simulation.organizations.item.copRequest.simulate.item collection</summary>
        /// <param name="position">The type of simulation to run.</param>
        /// <returns>A <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder"/></returns>
        public global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("cop%2Dsimulation%2Dtype", position);
                return new global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.Item.CopSimulationTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.SimulateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SimulateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request/simulate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Simulation.Organizations.Item.CopRequest.Simulate.SimulateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SimulateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/simulation/organizations/{organization%2Did}/cop-request/simulate", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
