// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.Workflows
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowsGetResponse_workflows_workflowRules
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "allow-zero-directors")]
        #pragma warning disable CS1591
        AllowZeroDirectors,
        #pragma warning restore CS1591
        [EnumMember(Value = "allow-missing-directors")]
        #pragma warning disable CS1591
        AllowMissingDirectors,
        #pragma warning restore CS1591
    }
}
