// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.LegalPersons.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.LegalPersons
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\legal-persons
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LegalPersonsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Griffin.Client.v0.legalPersons.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.LegalPersonItemRequestBuilder"/></returns>
        public global::Griffin.Client.V0.LegalPersons.Item.LegalPersonItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("legal%2Dperson%2Did", position);
                return new global::Griffin.Client.V0.LegalPersons.Item.LegalPersonItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.LegalPersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegalPersonsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/legal-persons", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.LegalPersonsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LegalPersonsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/legal-persons", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
