// <auto-generated/>
#pragma warning disable CS0618
using Griffin.Client.V0.Organizations.Item.Onboarding.Applications;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Griffin.Client.V0.Organizations.Item.Onboarding
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\organizations\{organization-id}\onboarding
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OnboardingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applications property</summary>
        public global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Griffin.Client.V0.Organizations.Item.Onboarding.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Onboarding.OnboardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OnboardingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/onboarding", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Onboarding.OnboardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OnboardingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/onboarding", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
