// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Workflows.Item
{
    /// <summary>Specifies if the legal person is an `individual` or a `corporation`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowGetResponse_legalPersonType
    {
        [EnumMember(Value = "individual")]
        #pragma warning disable CS1591
        Individual,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation")]
        #pragma warning disable CS1591
        Corporation,
        #pragma warning restore CS1591
    }
}
