// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search
{
    /// <summary>
    /// Shows the [account balance](/docs/terms/account-balance).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchPostResponse_searchResults_accountBalance : IParsable
    {
        /// <summary>The currency property</summary>
        public global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance_currency? Currency { get; set; }
        /// <summary>The value as a decimal-formatted string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance"/> and sets the default values.
        /// </summary>
        public SearchPostResponse_searchResults_accountBalance()
        {
            Currency = global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance_currency.GBP;
            Value = "1.00";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetEnumValue<global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance_currency>(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search.SearchPostResponse_searchResults_accountBalance_currency>("currency", Currency);
            writer.WriteStringValue("value", Value);
        }
    }
}
#pragma warning restore CS0618
