// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.Bank.Accounts.Search
{
    /// <summary>Specifies the type of savings account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchPostResponse_searchResults_savingsType
    {
        [EnumMember(Value = "easy-access")]
        #pragma warning disable CS1591
        EasyAccess,
        #pragma warning restore CS1591
        [EnumMember(Value = "bare-trust")]
        #pragma warning disable CS1591
        BareTrust,
        #pragma warning restore CS1591
    }
}
