// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Griffin.Client.V0.Organizations.Item.LegalPersons.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \v0\organizations\{organization-id}\legal-persons\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/legal-persons/search{?filter%5Blegal%2Dperson%2Dstatus%5D%5Beq%5D*,include*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0/organizations/{organization%2Did}/legal-persons/search{?filter%5Blegal%2Dperson%2Dstatus%5D%5Beq%5D*,include*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of legal persons whose legal names match the `search-query` supplied in the request.                 Takes an optional &apos;equals onboarded&apos; filter.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostResponse?> PostAsSearchPostResponseAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostResponse> PostAsSearchPostResponseAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of legal persons whose legal names match the `search-query` supplied in the request.                 Takes an optional &apos;equals onboarded&apos; filter.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsSearchPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchResponse?> PostAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchResponse> PostAsync(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchResponse>(requestInfo, global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of legal persons whose legal names match the `search-query` supplied in the request.                 Takes an optional &apos;equals onboarded&apos; filter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchPostRequestBody body, Action<RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of legal persons whose legal names match the `search-query` supplied in the request.                 Takes an optional &apos;equals onboarded&apos; filter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchRequestBuilderPostQueryParameters 
        {
            /// <summary>Return only legal persons with the given legal-person-status.</summary>
            [Obsolete("This property is deprecated, use FilterlegalPersonStatuseqAsPostFilterLegalPersonStatusEqQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Beq%5D")]
            public string? FilterlegalPersonStatuseq { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Beq%5D")]
            public string FilterlegalPersonStatuseq { get; set; }
#endif
            /// <summary>Return only legal persons with the given legal-person-status.</summary>
            [QueryParameter("filter%5Blegal%2Dperson%2Dstatus%5D%5Beq%5D")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.PostFilterLegalPersonStatusEqQueryParameterType? FilterlegalPersonStatuseqAsPostFilterLegalPersonStatusEqQueryParameterType { get; set; }
            /// <summary>For each legal person returned, include any roles in companies (significant control or directorship) in the response under the `included` attribute.</summary>
            [Obsolete("This property is deprecated, use IncludeAsPostIncludeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string[] Include { get; set; }
#endif
            /// <summary>For each legal person returned, include any roles in companies (significant control or directorship) in the response under the `included` attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.PostIncludeQueryParameterType[]? IncludeAsPostIncludeQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.PostIncludeQueryParameterType[] IncludeAsPostIncludeQueryParameterType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Griffin.Client.V0.Organizations.Item.LegalPersons.Search.SearchRequestBuilder.SearchRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
