// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Verifications.Item.Profiles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProfilesGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The verificationRelatedPartyProfiles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationRelatedPartyProfiles>? VerificationRelatedPartyProfiles { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationRelatedPartyProfiles> VerificationRelatedPartyProfiles { get; set; }
#endif
        /// <summary>The verificationSubjectProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationSubjectProfile? VerificationSubjectProfile { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationSubjectProfile VerificationSubjectProfile { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse"/> and sets the default values.
        /// </summary>
        public ProfilesGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "verification-related-party-profiles", n => { VerificationRelatedPartyProfiles = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationRelatedPartyProfiles>(global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationRelatedPartyProfiles.CreateFromDiscriminatorValue)?.AsList(); } },
                { "verification-subject-profile", n => { VerificationSubjectProfile = n.GetObjectValue<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationSubjectProfile>(global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationSubjectProfile.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationRelatedPartyProfiles>("verification-related-party-profiles", VerificationRelatedPartyProfiles);
            writer.WriteObjectValue<global::Griffin.Client.V0.Verifications.Item.Profiles.ProfilesGetResponse_verificationSubjectProfile>("verification-subject-profile", VerificationSubjectProfile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
