// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Decisions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DecisionsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Free-text field to explain the reasons behind the decision.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DecisionNotes { get; set; }
#nullable restore
#else
        public string DecisionNotes { get; set; }
#endif
        /// <summary>The decisionOutcome property</summary>
        public global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody_decisionOutcome? DecisionOutcome { get; set; }
        /// <summary>A link to the [verification](#tag/Verifications).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerificationUrl { get; set; }
#nullable restore
#else
        public string VerificationUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody"/> and sets the default values.
        /// </summary>
        public DecisionsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "decision-notes", n => { DecisionNotes = n.GetStringValue(); } },
                { "decision-outcome", n => { DecisionOutcome = n.GetEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody_decisionOutcome>(); } },
                { "verification-url", n => { VerificationUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("decision-notes", DecisionNotes);
            writer.WriteEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsPostRequestBody_decisionOutcome>("decision-outcome", DecisionOutcome);
            writer.WriteStringValue("verification-url", VerificationUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
