// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.LegalPersons.Item.Decisions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DecisionsGetResponse_decisions : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO 8601 formatted date-time.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Indicates if the decision was automated or made by a human.</summary>
        public global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionMaker? DecisionMaker { get; set; }
        /// <summary>Free-text field to explain the reasons behind the decision.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DecisionNotes { get; set; }
#nullable restore
#else
        public string DecisionNotes { get; set; }
#endif
        /// <summary>Indicates that an Ops user has created the decision.</summary>
        public global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOpsUser? DecisionOpsUser { get; set; }
        /// <summary>The decisionOutcome property</summary>
        public global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOutcome? DecisionOutcome { get; set; }
        /// <summary>Link to the [user](#tag/Users) that made the decision (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DecisionUserUrl { get; set; }
#nullable restore
#else
        public string DecisionUserUrl { get; set; }
#endif
        /// <summary>Username of the [user](#tag/Users) that made the decision (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DecisionUserUsername { get; set; }
#nullable restore
#else
        public string DecisionUserUsername { get; set; }
#endif
        /// <summary>A contextual link to the [legal person](#tag/Legal-persons).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalPersonUrl { get; set; }
#nullable restore
#else
        public string LegalPersonUrl { get; set; }
#endif
        /// <summary>A link to the [verification](#tag/Verifications).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerificationUrl { get; set; }
#nullable restore
#else
        public string VerificationUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions"/> and sets the default values.
        /// </summary>
        public DecisionsGetResponse_decisions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "decision-maker", n => { DecisionMaker = n.GetEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionMaker>(); } },
                { "decision-notes", n => { DecisionNotes = n.GetStringValue(); } },
                { "decision-ops-user", n => { DecisionOpsUser = n.GetEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOpsUser>(); } },
                { "decision-outcome", n => { DecisionOutcome = n.GetEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOutcome>(); } },
                { "decision-user-url", n => { DecisionUserUrl = n.GetStringValue(); } },
                { "decision-user-username", n => { DecisionUserUsername = n.GetStringValue(); } },
                { "legal-person-url", n => { LegalPersonUrl = n.GetStringValue(); } },
                { "verification-url", n => { VerificationUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionMaker>("decision-maker", DecisionMaker);
            writer.WriteStringValue("decision-notes", DecisionNotes);
            writer.WriteEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOpsUser>("decision-ops-user", DecisionOpsUser);
            writer.WriteEnumValue<global::Griffin.Client.V0.LegalPersons.Item.Decisions.DecisionsGetResponse_decisions_decisionOutcome>("decision-outcome", DecisionOutcome);
            writer.WriteStringValue("decision-user-url", DecisionUserUrl);
            writer.WriteStringValue("decision-user-username", DecisionUserUsername);
            writer.WriteStringValue("legal-person-url", LegalPersonUrl);
            writer.WriteStringValue("verification-url", VerificationUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
