// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item.Payments.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Present only when the request uses the `include` parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_included? Included { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_included Included { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_meta? Meta { get; set; }
#nullable restore
#else
        public global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_meta Meta { get; set; }
#endif
        /// <summary>The searchResults property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_searchResults>? SearchResults { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_searchResults> SearchResults { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse"/> and sets the default values.
        /// </summary>
        public SearchPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "included", n => { Included = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_included>(global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_included.CreateFromDiscriminatorValue); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_meta>(global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_meta.CreateFromDiscriminatorValue); } },
                { "search-results", n => { SearchResults = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_searchResults>(global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_searchResults.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_included>("included", Included);
            writer.WriteObjectValue<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_meta>("meta", Meta);
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.Payments.Search.SearchPostResponse_searchResults>("search-results", SearchResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
