// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.IndexNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IndexGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The resource path for the API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyUrl { get; set; }
#nullable restore
#else
        public string ApiKeyUrl { get; set; }
#endif
        /// <summary>Link to the [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationsUrl { get; set; }
#nullable restore
#else
        public string OrganizationsUrl { get; set; }
#endif
        /// <summary>Link to the [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationUrl { get; set; }
#nullable restore
#else
        public string OrganizationUrl { get; set; }
#endif
        /// <summary>The rolesUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RolesUrl { get; set; }
#nullable restore
#else
        public string RolesUrl { get; set; }
#endif
        /// <summary>The sessionUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionUrl { get; set; }
#nullable restore
#else
        public string SessionUrl { get; set; }
#endif
        /// <summary>The usersUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsersUrl { get; set; }
#nullable restore
#else
        public string UsersUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Griffin.Client.V0.IndexNamespace.IndexGetResponse"/> and sets the default values.
        /// </summary>
        public IndexGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.IndexNamespace.IndexGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.IndexNamespace.IndexGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.IndexNamespace.IndexGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api-key-url", n => { ApiKeyUrl = n.GetStringValue(); } },
                { "organization-url", n => { OrganizationUrl = n.GetStringValue(); } },
                { "organizations-url", n => { OrganizationsUrl = n.GetStringValue(); } },
                { "roles-url", n => { RolesUrl = n.GetStringValue(); } },
                { "session-url", n => { SessionUrl = n.GetStringValue(); } },
                { "users-url", n => { UsersUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api-key-url", ApiKeyUrl);
            writer.WriteStringValue("organizations-url", OrganizationsUrl);
            writer.WriteStringValue("organization-url", OrganizationUrl);
            writer.WriteStringValue("roles-url", RolesUrl);
            writer.WriteStringValue("session-url", SessionUrl);
            writer.WriteStringValue("users-url", UsersUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
