// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.Organizations.Item.Bank.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProductsGetResponse_bankAccountProducts_ownerType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "individual")]
        #pragma warning disable CS1591
        Individual,
        #pragma warning restore CS1591
        [EnumMember(Value = "corporation")]
        #pragma warning disable CS1591
        Corporation,
        #pragma warning restore CS1591
    }
}
