// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Griffin.Client.V0.Organizations.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrganizationGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The subset of [roles](#tag/Roles) available to [members](#tag/Members) of this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_availableRoles>? AvailableRoles { get; set; }
#nullable restore
#else
        public List<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_availableRoles> AvailableRoles { get; set; }
#endif
        /// <summary>The mutable display name for the Organisation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The organizationApiKeysUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationApiKeysUrl { get; set; }
#nullable restore
#else
        public string OrganizationApiKeysUrl { get; set; }
#endif
        /// <summary>Link to the [bank account](#tag/Bank-accounts) products owned by this [organization](#tag/Organization).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationBankAccountProductsUrl { get; set; }
#nullable restore
#else
        public string OrganizationBankAccountProductsUrl { get; set; }
#endif
        /// <summary>Link to search [bank accounts](#tag/Bank-accounts) associated with this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationBankAccountsSearchUrl { get; set; }
#nullable restore
#else
        public string OrganizationBankAccountsSearchUrl { get; set; }
#endif
        /// <summary>Link to the [bank accounts](#tag/Bank-accounts) managed by this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationBankAccountsUrl { get; set; }
#nullable restore
#else
        public string OrganizationBankAccountsUrl { get; set; }
#endif
        /// <summary>The organizationCorporationsUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationCorporationsUrl { get; set; }
#nullable restore
#else
        public string OrganizationCorporationsUrl { get; set; }
#endif
        /// <summary>Link to the endpoint which lists an organization&apos;s events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationEventsUrl { get; set; }
#nullable restore
#else
        public string OrganizationEventsUrl { get; set; }
#endif
        /// <summary>The organizationIndividualsUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationIndividualsUrl { get; set; }
#nullable restore
#else
        public string OrganizationIndividualsUrl { get; set; }
#endif
        /// <summary>Link to the resource that enables you to [invite](#tag/Invites) new [users](#tag/Users) to this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationInvitationsUrl { get; set; }
#nullable restore
#else
        public string OrganizationInvitationsUrl { get; set; }
#endif
        /// <summary>Link to search [legal persons](#tag/Legal-persons) grouped under this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationLegalPersonsSearchUrl { get; set; }
#nullable restore
#else
        public string OrganizationLegalPersonsSearchUrl { get; set; }
#endif
        /// <summary>Link to the [legal persons](#tag/Legal-persons) grouped under this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationLegalPersonsUrl { get; set; }
#nullable restore
#else
        public string OrganizationLegalPersonsUrl { get; set; }
#endif
        /// <summary>Link to the resource that enables you to request live access.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationLiveAccessUrl { get; set; }
#nullable restore
#else
        public string OrganizationLiveAccessUrl { get; set; }
#endif
        /// <summary>Link to the [memberships](#tag/Memberships) for this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationMembershipsUrl { get; set; }
#nullable restore
#else
        public string OrganizationMembershipsUrl { get; set; }
#endif
        /// <summary>The organization can either be a sandbox organization or a live one; Check out our guide for [sandbox mode vs live mode](/docs/guides/sandbox-vs-live-mode).</summary>
        public global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_organizationMode? OrganizationMode { get; set; }
        /// <summary>Link to the [Reliance onboarding](#tag/Reliance-onboarding).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationOnboardingApplicationsUrl { get; set; }
#nullable restore
#else
        public string OrganizationOnboardingApplicationsUrl { get; set; }
#endif
        /// <summary>Link to search [payments](#tag/Payments) associated with this organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationPaymentsSearchUrl { get; set; }
#nullable restore
#else
        public string OrganizationPaymentsSearchUrl { get; set; }
#endif
        /// <summary>Link to the [payments](#tag/Payments) associated with this organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationPaymentsUrl { get; set; }
#nullable restore
#else
        public string OrganizationPaymentsUrl { get; set; }
#endif
        /// <summary>Link to the [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationUrl { get; set; }
#nullable restore
#else
        public string OrganizationUrl { get; set; }
#endif
        /// <summary>Link to the endpoint which enables webhook creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationWebhooksUrl { get; set; }
#nullable restore
#else
        public string OrganizationWebhooksUrl { get; set; }
#endif
        /// <summary>Link to the onboarding [workflows](#tag/Workflows) configured for this [organization](#tag/Organizations).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationWorkflowsUrl { get; set; }
#nullable restore
#else
        public string OrganizationWorkflowsUrl { get; set; }
#endif
        /// <summary>Link to the [legal person](#tag/Legal-persons) that represents the [organization](#tag/Organizations); this can be an individual or a company.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnLegalPersonUrl { get; set; }
#nullable restore
#else
        public string OwnLegalPersonUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available-roles", n => { AvailableRoles = n.GetCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_availableRoles>(global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_availableRoles.CreateFromDiscriminatorValue)?.AsList(); } },
                { "display-name", n => { DisplayName = n.GetStringValue(); } },
                { "organization-api-keys-url", n => { OrganizationApiKeysUrl = n.GetStringValue(); } },
                { "organization-bank-account-products-url", n => { OrganizationBankAccountProductsUrl = n.GetStringValue(); } },
                { "organization-bank-accounts-search-url", n => { OrganizationBankAccountsSearchUrl = n.GetStringValue(); } },
                { "organization-bank-accounts-url", n => { OrganizationBankAccountsUrl = n.GetStringValue(); } },
                { "organization-corporations-url", n => { OrganizationCorporationsUrl = n.GetStringValue(); } },
                { "organization-events-url", n => { OrganizationEventsUrl = n.GetStringValue(); } },
                { "organization-individuals-url", n => { OrganizationIndividualsUrl = n.GetStringValue(); } },
                { "organization-invitations-url", n => { OrganizationInvitationsUrl = n.GetStringValue(); } },
                { "organization-legal-persons-search-url", n => { OrganizationLegalPersonsSearchUrl = n.GetStringValue(); } },
                { "organization-legal-persons-url", n => { OrganizationLegalPersonsUrl = n.GetStringValue(); } },
                { "organization-live-access-url", n => { OrganizationLiveAccessUrl = n.GetStringValue(); } },
                { "organization-memberships-url", n => { OrganizationMembershipsUrl = n.GetStringValue(); } },
                { "organization-mode", n => { OrganizationMode = n.GetEnumValue<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_organizationMode>(); } },
                { "organization-onboarding-applications-url", n => { OrganizationOnboardingApplicationsUrl = n.GetStringValue(); } },
                { "organization-payments-search-url", n => { OrganizationPaymentsSearchUrl = n.GetStringValue(); } },
                { "organization-payments-url", n => { OrganizationPaymentsUrl = n.GetStringValue(); } },
                { "organization-url", n => { OrganizationUrl = n.GetStringValue(); } },
                { "organization-webhooks-url", n => { OrganizationWebhooksUrl = n.GetStringValue(); } },
                { "organization-workflows-url", n => { OrganizationWorkflowsUrl = n.GetStringValue(); } },
                { "own-legal-person-url", n => { OwnLegalPersonUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_availableRoles>("available-roles", AvailableRoles);
            writer.WriteStringValue("display-name", DisplayName);
            writer.WriteStringValue("organization-api-keys-url", OrganizationApiKeysUrl);
            writer.WriteStringValue("organization-bank-account-products-url", OrganizationBankAccountProductsUrl);
            writer.WriteStringValue("organization-bank-accounts-search-url", OrganizationBankAccountsSearchUrl);
            writer.WriteStringValue("organization-bank-accounts-url", OrganizationBankAccountsUrl);
            writer.WriteStringValue("organization-corporations-url", OrganizationCorporationsUrl);
            writer.WriteStringValue("organization-events-url", OrganizationEventsUrl);
            writer.WriteStringValue("organization-individuals-url", OrganizationIndividualsUrl);
            writer.WriteStringValue("organization-invitations-url", OrganizationInvitationsUrl);
            writer.WriteStringValue("organization-legal-persons-search-url", OrganizationLegalPersonsSearchUrl);
            writer.WriteStringValue("organization-legal-persons-url", OrganizationLegalPersonsUrl);
            writer.WriteStringValue("organization-live-access-url", OrganizationLiveAccessUrl);
            writer.WriteStringValue("organization-memberships-url", OrganizationMembershipsUrl);
            writer.WriteEnumValue<global::Griffin.Client.V0.Organizations.Item.OrganizationGetResponse_organizationMode>("organization-mode", OrganizationMode);
            writer.WriteStringValue("organization-onboarding-applications-url", OrganizationOnboardingApplicationsUrl);
            writer.WriteStringValue("organization-payments-search-url", OrganizationPaymentsSearchUrl);
            writer.WriteStringValue("organization-payments-url", OrganizationPaymentsUrl);
            writer.WriteStringValue("organization-url", OrganizationUrl);
            writer.WriteStringValue("organization-webhooks-url", OrganizationWebhooksUrl);
            writer.WriteStringValue("organization-workflows-url", OrganizationWorkflowsUrl);
            writer.WriteStringValue("own-legal-person-url", OwnLegalPersonUrl);
        }
    }
}
#pragma warning restore CS0618
