// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Griffin.Client.V0.LegalPersons.Item
{
    /// <summary>Status of the [legal person](#tag/Legal-persons)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LegalPersonPutResponse_legalPersonStatus
    {
        [EnumMember(Value = "restricted")]
        #pragma warning disable CS1591
        Restricted,
        #pragma warning restore CS1591
        [EnumMember(Value = "onboarding-declined")]
        #pragma warning disable CS1591
        OnboardingDeclined,
        #pragma warning restore CS1591
        [EnumMember(Value = "onboarded")]
        #pragma warning disable CS1591
        Onboarded,
        #pragma warning restore CS1591
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "onboarding")]
        #pragma warning disable CS1591
        Onboarding,
        #pragma warning restore CS1591
    }
}
